@echo off
setlocal ENABLEDELAYEDEXPANSION

"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+3+news+articles+from+the+last+week+that+mention+Red+Hat&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+3+news+articles+from+the+last+week+that+mention+Azure&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+3+news+articles+from+the+last+week+that+mention+Pure+Storage&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+3+news+articles+from+the+last+week+that+mention+VMware&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Dell&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+IBM&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+HPE&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Google&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Microsoft&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Nvidia&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Rubrik&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+OpenAI&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Anthropic&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Meta&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+AWS&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Grok&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Snowflake&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Databricks&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+VAST+Data&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+NetApp&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+CNCF&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Kubernetes&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Mistral&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Perplexity&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+WitnessAI&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+IonQ&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+D-Wave&source=chat-user-bubble-copy-link"
"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "https://saleschat.dell.com/chat?chatAgent=FAST^&message=show+me+a+summary+of+the+top+5+news+articles+from+the+last+week+that+mention+Quantum&source=chat-user-bubble-copy-link"



rem ADVANCED URL with all % escaped as %% and & escaped as ^&
set "ADV_URL=https://saleschat.dell.com/chat?chatAgent=ADVANCED^&message=Act+as+an+intelligence+analyst+specializing+in+Dell+Technologies+Enterprise+Storage%%2C+HCI%%2C+Edge%%2C+and+Cloud+Platform+solutions.+Your+task+is+to+find+the+most+recent+collateral+developed+in+the+last+week+for+the+following+platforms%%3A+%%22PowerMax%%22%%2C+%%22PowerStore%%22%%2C+%%22PowerFlex%%2C+%%22NativeEdge%%22%%2C+%%22Dell+Automated+Platform+%%28DAP%%29%%22%%2C+%%22Dell+Private+Cloud+for+VMware%%22%%2C+%%22Dell+Private+Cloud+for+OpenShift%%22%%2C+%%22Azure+Local%%22%%2C+%%22Nutanix+XC%%22%%2C+%%22Nutanix+XC+Plus%%22+%%0A**Primary+Objective%%3A**+Prioritize+any+content+that+explicitly+discusses%%3A+%%22What%%27s+New%%22+recent+software%%2Fhardware+updates+%%28e.g.%%2C+new+PowerMaxOS%%2C+PowerStoreOS%%2C+or+PowerFlex+releases%%29+new+reference+architectures%%2C+or+validated+designs+related+to+these+platforms.+%%0A**Constraints%%3A**+%%0ATimeframe%%3A+Focus+*only*+on+content+published+or+updated+within+the+last+week.+%%0ASource+Type%%3A+Search+for+official+Dell-produced+content+%%28internal+or+external%%29+or+content+from+major+vendor+partners+%%28e.g.%%2C+VMware%%2C+Red+Hat%%2C+Microsoft%%2C+Intel%%2C+Nutanix%%29.+%%0AContent+Type%%3A+Include+solution+briefs%%2C+white+papers%%2C+reference+architectures%%2C+validated+designs%%2C+official+presentations+%%28e.g.%%2C+from+Dell+events%%2C+internal+sales+kickoffs%%29%%2C+technical+specifications+sheets%%2C+and+detailed+official+blog+posts.+%%0A**Output+Format%%3A**+Deliver+the+findings+in+a+markdown+table+with+the+following+columns.+Make+sure+the+table+is+complete%%3A+%%0AContent+Title%%3A+The+official+name+of+the+document+or+presentation.+%%0ASummary%%3A+A+concise+summary+%%282-3+sentences+or+bullet+points%%29+detailing+the+content%%27s+key+objectives+and%%2C+most+importantly%%2C+any+specific+%%22What%%27s+New%%22+features%%2C+hardware%%2C+software+versions%%2C+or+partner+integrations+mentioned.+%%0AContent+Type%%3A+%%28e.g.%%2C+White+Paper%%2C+Reference+Architecture%%2C+Presentation%%29+Date%%3A+The+publication+or+%%22last+modified%%22+date.+Source%%2FLink%%3A+A+direct+link+to+the+content+or+its+internal+repository+location.+%%0A**Executive+Summary%%3A**+In+addition+to+the+tabular+output%%2C+provide+a+concise+executive+summary+of+all+the+items&source=chat-user-bubble-copy-link"

"C:\Windows\System32\rundll32.exe" url.dll,FileProtocolHandler "!ADV_URL!"

endlocal